sonar.projectKey=aissamnasri
sonar.organization=aissamnasri

sonar.projectName=MicroCRM

# Sources
sonar.sources=back/src/main,front/src

# Tests
sonar.tests=back/src/test

# Classes Java compilées
sonar.java.binaries=back/build/classes/java/main

# Couverture backend Spring Boot / JaCoCo
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml

# Couverture frontend Angular / LCOV
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info

sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.coverage.exclusions=**/*.spec.ts,**/config/**,**/*Application.java